double perform_fit(vars_struct data, mp_par *pars, double *a, double *uncert, double *covar, int n_coef, int code);
void initialize_pars(mp_par *pars, double *a, vars_struct data, int n_coef);
void shutoff_temp (mp_par *pars, vars_struct data);
void shutoff_temp2 (mp_par *pars,  vars_struct data);
void shutoff_temp3 (mp_par *pars,  vars_struct data);
void shutoff_vel_except_iron  (mp_par *pars, vars_struct data);
void fit_only_star(int star_no, mp_par *pars, vars_struct data);
void shutoff_distances(mp_par *pars, vars_struct data);
void shutoff_star(int star_no, mp_par *pars, vars_struct data);
void shutoff_global (mp_par *pars, vars_struct data);
void shutoff_sn_pars (mp_par *pars, vars_struct data);
void shutoff_vel_all(mp_par *pars, vars_struct data);
void shutoff_vel_star(int star_no, mp_par *pars, vars_struct data);
void set_star_coef (double *a, vars_struct data, int coef_no, double val);
void shutoff_star_coef (mp_par *pars, vars_struct data, int coef_no);
void shutoff_extinction_coef(mp_par *pars, vars_struct data);
void vary_full_reddening_law(mp_par *pars, vars_struct &data);
void vary_only_rv(mp_par *pars, vars_struct &data);
void set_cardelli(double *a, vars_struct data, double rv);
void set_filter_coef (double *a, vars_struct data, int coef_no, double val);
double calculate_single_chi2(int fit_star_no, double *a, vars_struct data, int &single_nphot, int &single_nvel);
bool is_blocked_direct(vars_struct data, double *a, int i);
